name: "PR Tracker Test"
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mateusabelli/pr-tracker@main
        with:
          who-to-greet: "Mateus"
          owner: ${{ github.repository_owner}}
          repository: ${{ github.event.repository.name }}
